class CulturasAddModulo < ActiveRecord::Migration[5.2]
  def change
  	add_column :culturas, :m1_p1, :string
	add_column :culturas, :m1_p2, :string
	add_column :culturas, :m1_p3_1, :string
	add_column :culturas, :m1_p3_2, :string
	add_column :culturas, :m1_p3_3, :string
	add_column :culturas, :m1_p3_4, :string
	add_column :culturas, :m1_p3_5, :string
	add_column :culturas, :m1_p3_6, :string
	add_column :culturas, :m1_p3_7, :string
	add_column :culturas, :m1_p3_8, :string
	add_column :culturas, :m1_p4, :string
	add_column :culturas, :m1_p5, :string
	add_column :culturas, :m1_p6_1, :string
	add_column :culturas, :m1_p6_2, :string
	add_column :culturas, :m1_p6_3, :string
	add_column :culturas, :m1_p6_4, :string
	add_column :culturas, :m1_p6_5, :string
	add_column :culturas, :m1_p6_6, :string
	add_column :culturas, :m1_p7, :string
	add_column :culturas, :m1_p8_1, :string
	add_column :culturas, :m1_p8_2, :string
	add_column :culturas, :m1_p8_3, :string
	add_column :culturas, :m1_p8_4, :string
	add_column :culturas, :m1_p8_5, :string
	add_column :culturas, :m1_p9_1, :string
	add_column :culturas, :m1_p9_2, :string
	add_column :culturas, :m1_p9_3, :string
	add_column :culturas, :m1_p9_4, :string
	add_column :culturas, :m1_p9_5, :string
	add_column :culturas, :m1_p10, :string
	add_column :culturas, :m1_p11, :string
	add_column :culturas, :m1_p12_1, :string
	add_column :culturas, :m1_p12_2, :string
	add_column :culturas, :m1_p12_3, :string
	add_column :culturas, :m1_p12_4, :string
	add_column :culturas, :m1_p12_5, :string
	add_column :culturas, :m1_p12_6, :string
	add_column :culturas, :m1_p12_7, :string
	add_column :culturas, :m1_p12_8, :string
	add_column :culturas, :m2_p1, :string
	add_column :culturas, :m2_p2_1, :string
	add_column :culturas, :m2_p2_2, :string
	add_column :culturas, :m2_p2_3, :string
	add_column :culturas, :m2_p2_4, :string
	add_column :culturas, :m2_p3, :string
	add_column :culturas, :m2_p4, :string
	add_column :culturas, :m2_p5_1, :string
	add_column :culturas, :m2_p5_2, :string
	add_column :culturas, :m2_p5_3, :string
	add_column :culturas, :m2_p5_4, :string
	add_column :culturas, :m2_p5_5, :string
	add_column :culturas, :m2_p5_6, :string
	add_column :culturas, :m2_p6, :string
	add_column :culturas, :m2_p7, :string
	add_column :culturas, :m2_p8, :string
	add_column :culturas, :m2_p8_1, :string
	add_column :culturas, :m2_p9, :string
	add_column :culturas, :m2_p10, :string
	add_column :culturas, :m2_p11, :string
	add_column :culturas, :m2_p12, :string
	add_column :culturas, :m2_p13, :string
	add_column :culturas, :m2_p14, :string
	add_column :culturas, :m2_p15, :string
	add_column :culturas, :m2_p16_1, :string
	add_column :culturas, :m2_p16_2, :string
	add_column :culturas, :m2_p16_3, :string
	add_column :culturas, :m2_p16_4, :string
	add_column :culturas, :m2_p16_5, :string
	add_column :culturas, :m2_p16_6, :string
	add_column :culturas, :m2_p16_7, :string
	add_column :culturas, :m2_p16_8, :string
	add_column :culturas, :m2_p17, :string
	add_column :culturas, :m3_p1_1, :string
	add_column :culturas, :m3_p1_2, :string
	add_column :culturas, :m3_p1_3, :string
	add_column :culturas, :m3_p1_4, :string
	add_column :culturas, :m3_p1_5, :string
	add_column :culturas, :m3_p2_1, :string
	add_column :culturas, :m3_p2_2, :string
	add_column :culturas, :m3_p2_3, :string
	add_column :culturas, :m3_p2_4, :string
	add_column :culturas, :m3_p2_5, :string
	add_column :culturas, :m3_p2_6, :string
	add_column :culturas, :m3_p2_7, :string
	add_column :culturas, :m3_p2_8, :string
	add_column :culturas, :m3_p2_9, :string
	add_column :culturas, :m3_p2_10, :string
	add_column :culturas, :m3_p2_11, :string
	add_column :culturas, :m3_p3_1, :string
	add_column :culturas, :m3_p3_2, :string
	add_column :culturas, :m3_p3_3, :string
	add_column :culturas, :m3_p3_4, :string
	add_column :culturas, :m3_p3_5, :string
	add_column :culturas, :m3_p3_6, :string
	add_column :culturas, :m3_p3_7, :string
	add_column :culturas, :m3_p3_8, :string
	add_column :culturas, :m3_p3_9, :string
	add_column :culturas, :m3_p4_1, :string
	add_column :culturas, :m3_p4_2, :string
	add_column :culturas, :m3_p4_3, :string
	add_column :culturas, :m3_p4_4, :string
	add_column :culturas, :m3_p5, :string
	add_column :culturas, :m3_p6, :string
	add_column :culturas, :m3_p7, :string
	add_column :culturas, :m3_p8, :string
	add_column :culturas, :m3_p9, :string
	add_column :culturas, :m3_p10, :string
	add_column :culturas, :m3_p11, :string
	add_column :culturas, :m4_p1_1, :string
	add_column :culturas, :m4_p1_2, :string
	add_column :culturas, :m4_p1_3, :string
	add_column :culturas, :m4_p1_4, :string
	add_column :culturas, :m4_p2_1, :string
	add_column :culturas, :m4_p2_2, :string
	add_column :culturas, :m4_p2_3, :string
	add_column :culturas, :m4_p2_4, :string
	add_column :culturas, :m4_p3_1, :string
	add_column :culturas, :m4_p3_2, :string
	add_column :culturas, :m4_p3_3, :string
	add_column :culturas, :m4_p3_4, :string
	add_column :culturas, :m4_p3_5, :string
	add_column :culturas, :m4_p4_1, :string
	add_column :culturas, :m4_p4_2, :string
	add_column :culturas, :m4_p4_3, :string
	add_column :culturas, :m4_p4_4, :string
	add_column :culturas, :m4_p4_5, :string
	add_column :culturas, :m4_p4_6, :string
	add_column :culturas, :m4_p4_7, :string
	add_column :culturas, :m4_p4_8, :string
	add_column :culturas, :m4_p4_9, :string
	add_column :culturas, :m4_p5_1, :string
	add_column :culturas, :m4_p5_2, :string
	add_column :culturas, :m4_p5_3, :string
	add_column :culturas, :m4_p5_4, :string
	add_column :culturas, :m4_p5_5, :string
	add_column :culturas, :m4_p6, :string
	add_column :culturas, :m4_p7_1, :string
	add_column :culturas, :m4_p7_2, :string
	add_column :culturas, :m4_p7_3, :string
	add_column :culturas, :m4_p7_4, :string
	add_column :culturas, :m4_p7_5, :string
  end
end
