class CulturasRemoveAddAll < ActiveRecord::Migration[5.2]
  def change

  	remove_column :culturas, :entrevistador, :string
  	remove_column :culturas, :critico, :string
  	remove_column :culturas, :supervisor, :string
  	remove_column :culturas, :digitador, :string

	add_column :culturas, :pa, :string
	add_column :culturas, :pb, :string
	add_column :culturas, :supervisor, :string
	add_column :culturas, :critico, :string
	add_column :culturas, :digitador, :string
	add_column :culturas, :fv_1, :string
	add_column :culturas, :fv_2, :string
	add_column :culturas, :fv_3, :string
	add_column :culturas, :fa, :string
	add_column :culturas, :hi, :string
	add_column :culturas, :hf, :string
	add_column :culturas, :pf, :string
	add_column :culturas, :pg1, :string
	add_column :culturas, :pg2, :string
	add_column :culturas, :pg3, :string
	add_column :culturas, :ph1, :string
	add_column :culturas, :ph2, :string
	add_column :culturas, :ph3, :string
	add_column :culturas, :pi, :string
	add_column :culturas, :p1, :string
	add_column :culturas, :p2, :string
	add_column :culturas, :p4a_1, :string
	add_column :culturas, :p4a_2, :string
	add_column :culturas, :p4a_3, :string
	add_column :culturas, :p4a_4, :string
	add_column :culturas, :p4a_5, :string
	add_column :culturas, :p4a_6, :string
	add_column :culturas, :p4a_7, :string
	add_column :culturas, :p4a_8, :string
	add_column :culturas, :p4b_1, :string
	add_column :culturas, :p4b_2, :string
	add_column :culturas, :p4b_3, :string
	add_column :culturas, :p4b_4, :string
	add_column :culturas, :p4b_5, :string
	add_column :culturas, :p4b_6, :string
	add_column :culturas, :p4b_7, :string
	add_column :culturas, :p4b_8, :string
	add_column :culturas, :p4c_1, :string
	add_column :culturas, :p4c_2, :string
	add_column :culturas, :p4c_3, :string
	add_column :culturas, :p4c_4, :string
	add_column :culturas, :p4c_5, :string
	add_column :culturas, :p4c_6, :string
	add_column :culturas, :p4c_7, :string
	add_column :culturas, :p4c_8, :string
	add_column :culturas, :p4d_1, :string
	add_column :culturas, :p4d_2, :string
	add_column :culturas, :p4d_3, :string
	add_column :culturas, :p4d_4, :string
	add_column :culturas, :p4d_5, :string
	add_column :culturas, :p4d_6, :string
	add_column :culturas, :p4d_7, :string
	add_column :culturas, :p4d_8, :string
	add_column :culturas, :p4e_1, :string
	add_column :culturas, :p4e_2, :string
	add_column :culturas, :p4e_3, :string
	add_column :culturas, :p4e_4, :string
	add_column :culturas, :p4e_5, :string
	add_column :culturas, :p4e_6, :string
	add_column :culturas, :p4e_7, :string
	add_column :culturas, :p4e_8, :string
	add_column :culturas, :p4f_1, :string
	add_column :culturas, :p4f_2, :string
	add_column :culturas, :p4f_3, :string
	add_column :culturas, :p4f_4, :string
	add_column :culturas, :p4f_5, :string
	add_column :culturas, :p4f_6, :string
	add_column :culturas, :p4f_7, :string
	add_column :culturas, :p4f_8, :string
	add_column :culturas, :p4g_1, :string
	add_column :culturas, :p4g_2, :string
	add_column :culturas, :p4g_3, :string
	add_column :culturas, :p4g_4, :string
	add_column :culturas, :p4g_5, :string
	add_column :culturas, :p4g_6, :string
	add_column :culturas, :p4g_7, :string
	add_column :culturas, :p4g_8, :string
	add_column :culturas, :p4h_1, :string
	add_column :culturas, :p4h_2, :string
	add_column :culturas, :p4h_3, :string
	add_column :culturas, :p4h_4, :string
	add_column :culturas, :p4h_5, :string
	add_column :culturas, :p4h_6, :string
	add_column :culturas, :p4h_7, :string
	add_column :culturas, :p4h_8, :string
	add_column :culturas, :p4i_1, :string
	add_column :culturas, :p4i_2, :string
	add_column :culturas, :p4i_3, :string
	add_column :culturas, :p4i_4, :string
	add_column :culturas, :p4i_5, :string
	add_column :culturas, :p4i_6, :string
	add_column :culturas, :p4i_7, :string
	add_column :culturas, :p4i_8, :string
	add_column :culturas, :p4j_1, :string
	add_column :culturas, :p4j_2, :string
	add_column :culturas, :p4j_3, :string
	add_column :culturas, :p4j_4, :string
	add_column :culturas, :p4j_5, :string
	add_column :culturas, :p4j_6, :string
	add_column :culturas, :p4j_7, :string
	add_column :culturas, :p4j_8, :string
	add_column :culturas, :p4k_1, :string
	add_column :culturas, :p4k_2, :string
	add_column :culturas, :p4k_3, :string
	add_column :culturas, :p4k_4, :string
	add_column :culturas, :p4k_5, :string
	add_column :culturas, :p4k_6, :string
	add_column :culturas, :p4k_7, :string
	add_column :culturas, :p4k_8, :string
	add_column :culturas, :p4l_1, :string
	add_column :culturas, :p4l_2, :string
	add_column :culturas, :p4l_3, :string
	add_column :culturas, :p4l_4, :string
	add_column :culturas, :p4l_5, :string
	add_column :culturas, :p4l_6, :string
	add_column :culturas, :p4l_7, :string
	add_column :culturas, :p4l_8, :string
	add_column :culturas, :p4m_1, :string
	add_column :culturas, :p4m_2, :string
	add_column :culturas, :p4m_3, :string
	add_column :culturas, :p4m_4, :string
	add_column :culturas, :p4m_5, :string
	add_column :culturas, :p4m_6, :string
	add_column :culturas, :p4m_7, :string
	add_column :culturas, :p4m_8, :string
	add_column :culturas, :p4n_1, :string
	add_column :culturas, :p4n_2, :string
	add_column :culturas, :p4n_3, :string
	add_column :culturas, :p4n_4, :string
	add_column :culturas, :p4n_5, :string
	add_column :culturas, :p4n_6, :string
	add_column :culturas, :p4n_7, :string
	add_column :culturas, :p4n_8, :string
	add_column :culturas, :p8, :string
	add_column :culturas, :p9, :string
	add_column :culturas, :p10, :string
	add_column :culturas, :p11, :string
	add_column :culturas, :p12, :string
	add_column :culturas, :p13, :string
	add_column :culturas, :p14_a, :string
	add_column :culturas, :p14_b, :string
	add_column :culturas, :p14_c, :string
	add_column :culturas, :p14_d, :string
	add_column :culturas, :p14_e, :string
	add_column :culturas, :p14_f, :string
	add_column :culturas, :p15, :string
	add_column :culturas, :p16_a, :string
	add_column :culturas, :p16_b, :string
	add_column :culturas, :p16_c, :string
	add_column :culturas, :p16_d, :string
	add_column :culturas, :p16_e, :string
	add_column :culturas, :p17_a, :string
	add_column :culturas, :p17_b, :string
	add_column :culturas, :p17_c, :string
	add_column :culturas, :p17_d, :string
	add_column :culturas, :p17_e, :string
	add_column :culturas, :p17_f, :string
	add_column :culturas, :p17_g, :string
	add_column :culturas, :p18_a, :string
	add_column :culturas, :p18_b, :string
	add_column :culturas, :p18_c, :string
	add_column :culturas, :p18_d, :string
	add_column :culturas, :p18_e, :string
	add_column :culturas, :p18_f, :string
	add_column :culturas, :p18_g, :string
	add_column :culturas, :p18_h, :string
	add_column :culturas, :p18_i, :string
	add_column :culturas, :p18_j, :string
	add_column :culturas, :p18_k, :string
	add_column :culturas, :p18_l, :string
	add_column :culturas, :p18_m, :string
	add_column :culturas, :p18_n, :string
	add_column :culturas, :p18_ñ, :string
	add_column :culturas, :p18_o, :string
	add_column :culturas, :p18_p, :string
	add_column :culturas, :p18_q, :string
	add_column :culturas, :p19_a, :string
	add_column :culturas, :p19_b, :string
	add_column :culturas, :p19_c, :string
	add_column :culturas, :p19_d, :string
	add_column :culturas, :p19_e, :string
	add_column :culturas, :p19_f, :string
	add_column :culturas, :p19_g, :string
	add_column :culturas, :p19_h, :string
	add_column :culturas, :p20_a, :string
	add_column :culturas, :p20_b, :string
	add_column :culturas, :p20_c, :string
	add_column :culturas, :p20_d, :string
	add_column :culturas, :p20_e, :string
	add_column :culturas, :p21_a, :string
	add_column :culturas, :p21_b, :string
	add_column :culturas, :p21_c, :string
	add_column :culturas, :p21_d, :string
	add_column :culturas, :p21_e, :string
	add_column :culturas, :p22, :string
	add_column :culturas, :p23_a, :string
	add_column :culturas, :p23_b, :string
	add_column :culturas, :p23_c, :string
	add_column :culturas, :p24_a, :string
	add_column :culturas, :p24_b, :string
	add_column :culturas, :p25_a, :string
	add_column :culturas, :p25_b, :string
	add_column :culturas, :p25_c, :string
	add_column :culturas, :p25_d, :string
	add_column :culturas, :p25_e, :string
	add_column :culturas, :p25_f, :string
	add_column :culturas, :p26, :string
	add_column :culturas, :p27_a, :string
	add_column :culturas, :p27_b, :string
	add_column :culturas, :p27_c, :string
	add_column :culturas, :p27_d, :string
	add_column :culturas, :p27_e, :string
	add_column :culturas, :p27_f, :string
	add_column :culturas, :p28_a, :string
	add_column :culturas, :p28_b, :string
	add_column :culturas, :p28_c, :string
	add_column :culturas, :p28_d, :string
	add_column :culturas, :p28_e, :string
	add_column :culturas, :p28_f, :string
	add_column :culturas, :p28_g, :string
	add_column :culturas, :p28_h, :string
	add_column :culturas, :p28_i, :string
	add_column :culturas, :p28_j, :string
	add_column :culturas, :p28_k, :string
	add_column :culturas, :p29_a, :string
	add_column :culturas, :p29_b, :string
	add_column :culturas, :p29_c, :string
	add_column :culturas, :p29_d, :string
	add_column :culturas, :p30, :string
	add_column :culturas, :p31_a, :string
	add_column :culturas, :p31_b, :string
	add_column :culturas, :p31_c, :string
	add_column :culturas, :p31_d, :string
	add_column :culturas, :p31_e, :string
	add_column :culturas, :p32, :string
	add_column :culturas, :p33, :string
	add_column :culturas, :p34_a, :string
	add_column :culturas, :p34_b, :string
	add_column :culturas, :p34_c, :string
	add_column :culturas, :p34_d, :string
	add_column :culturas, :p34_e, :string
	add_column :culturas, :p34_f, :string
	add_column :culturas, :p34_g, :string
	add_column :culturas, :p34_h, :string
	add_column :culturas, :p35, :string
	add_column :culturas, :p36, :string
	add_column :culturas, :p37_a, :string
	add_column :culturas, :p37_b, :string
	add_column :culturas, :p37_c, :string
	add_column :culturas, :p37_d, :string
	add_column :culturas, :p37_e, :string
	add_column :culturas, :p37_f, :string
	add_column :culturas, :p37_g, :string
	add_column :culturas, :p37_h, :string
	add_column :culturas, :p37_i, :string
	add_column :culturas, :p37_j, :string
	add_column :culturas, :p37_k, :string
	add_column :culturas, :p37_l, :string
	add_column :culturas, :p38_a, :string
	add_column :culturas, :p38_b, :string
	add_column :culturas, :p38_c, :string
	add_column :culturas, :p38_d, :string
	add_column :culturas, :p38_e, :string
	add_column :culturas, :p38_f, :string
	add_column :culturas, :p39_a, :string
	add_column :culturas, :p39_b, :string
	add_column :culturas, :p39_c, :string
	add_column :culturas, :p39_d, :string
	add_column :culturas, :p39_e, :string
	add_column :culturas, :p39_f, :string
	add_column :culturas, :p39_g, :string
	add_column :culturas, :p40, :string
	add_column :culturas, :p41_a, :string
	add_column :culturas, :p41_b, :string
	add_column :culturas, :p41_c, :string
	add_column :culturas, :p41_d, :string
	add_column :culturas, :p41_e, :string
	add_column :culturas, :p42_a, :string
	add_column :culturas, :p42_b, :string
	add_column :culturas, :p42_c, :string
	add_column :culturas, :p42_d, :string
	add_column :culturas, :p42_e, :string
	add_column :culturas, :p42_f, :string
	add_column :culturas, :p42_g, :string
	add_column :culturas, :p42_h, :string
	add_column :culturas, :p42_i, :string
	add_column :culturas, :p42_j, :string
	add_column :culturas, :p42_k, :string
	add_column :culturas, :p42_l, :string
	add_column :culturas, :p42_m, :string
	add_column :culturas, :p43, :string
	add_column :culturas, :p44, :string
	add_column :culturas, :p45_a, :string
	add_column :culturas, :p45_b, :string
	add_column :culturas, :p45_c, :string
	add_column :culturas, :p45_d, :string
	add_column :culturas, :p45_e, :string
	add_column :culturas, :p46_a, :string
	add_column :culturas, :p46_b, :string
	add_column :culturas, :p46_c, :string
	add_column :culturas, :p46_d, :string
	add_column :culturas, :p46_e, :string
	add_column :culturas, :p47, :string
	add_column :culturas, :p48_a, :string
	add_column :culturas, :p48_b, :string
	add_column :culturas, :p48_c, :string
	add_column :culturas, :p48_d, :string
	add_column :culturas, :p48_e, :string
	add_column :culturas, :p48_f, :string
	add_column :culturas, :p48_g, :string
	add_column :culturas, :p49, :string
	add_column :culturas, :p50, :string
	add_column :culturas, :p51, :string
	add_column :culturas, :p52, :string
	add_column :culturas, :p53, :string
	add_column :culturas, :p54, :string
	add_column :culturas, :p55_a, :string
	add_column :culturas, :p55_b, :string
	add_column :culturas, :p55_c, :string
	add_column :culturas, :p55_d, :string
	add_column :culturas, :p56, :string
	add_column :culturas, :p57_a, :string
	add_column :culturas, :p57_b, :string
	add_column :culturas, :p57_c, :string
	add_column :culturas, :p57_d, :string
	add_column :culturas, :p58_a, :string
	add_column :culturas, :p58_b, :string
	add_column :culturas, :p58_c, :string
	add_column :culturas, :p58_d, :string
	add_column :culturas, :p58_e, :string
	add_column :culturas, :p59, :string
	add_column :culturas, :p60_a, :string
	add_column :culturas, :p60_b, :string
	add_column :culturas, :p60_c, :string
	add_column :culturas, :p60_d, :string
	add_column :culturas, :p60_e, :string
	add_column :culturas, :p60_f, :string
	add_column :culturas, :p60_g, :string
	add_column :culturas, :p60_h, :string
	add_column :culturas, :p60_i, :string
	add_column :culturas, :p60_j, :string
	add_column :culturas, :p60_k, :string
	add_column :culturas, :p60_l, :string
	add_column :culturas, :p60_m, :string
	add_column :culturas, :p61, :string
	add_column :culturas, :p62_a, :string
	add_column :culturas, :p62_b, :string
	add_column :culturas, :p62_c, :string
	add_column :culturas, :p62_d, :string
	add_column :culturas, :p62_e, :string
	add_column :culturas, :p63_a, :string
	add_column :culturas, :p63_b, :string
	add_column :culturas, :p63_c, :string
	add_column :culturas, :p63_d, :string
	add_column :culturas, :p64, :string
	add_column :culturas, :p65_a, :string
	add_column :culturas, :p65_b, :string
	add_column :culturas, :p65_c, :string
	add_column :culturas, :p65_d, :string
	add_column :culturas, :p65_e, :string
	add_column :culturas, :p65_f, :string
	add_column :culturas, :p65_g, :string
	add_column :culturas, :p65_h, :string
	add_column :culturas, :p65_i, :string
	add_column :culturas, :p65_j, :string
	add_column :culturas, :p66, :string
	add_column :culturas, :p67, :string
	add_column :culturas, :p68, :string
	add_column :culturas, :p69_a, :string
	add_column :culturas, :p69_b, :string
	add_column :culturas, :p69_c, :string
	add_column :culturas, :p70_a, :string
	add_column :culturas, :p70_b, :string
	add_column :culturas, :p70_c, :string
	add_column :culturas, :p71, :string
	add_column :culturas, :p72, :string
	add_column :culturas, :p73, :string
	add_column :culturas, :p74, :string
	add_column :culturas, :p75, :string
	add_column :culturas, :p76_a, :string
	add_column :culturas, :p76_b, :string
	add_column :culturas, :p76_c, :string
	add_column :culturas, :p76_d, :string
	add_column :culturas, :p76_e, :string
	add_column :culturas, :p76_f, :string
	add_column :culturas, :p76_g, :string
	add_column :culturas, :p77, :string
	add_column :culturas, :p78, :string
	add_column :culturas, :p79, :string
	add_column :culturas, :p80, :string
	add_column :culturas, :p81_a, :string
	add_column :culturas, :p81_b, :string
	add_column :culturas, :p81_c, :string
	add_column :culturas, :p81_d, :string
	add_column :culturas, :p81_e, :string
	add_column :culturas, :p82, :string
	add_column :culturas, :p83_a, :string
	add_column :culturas, :p83_b, :string
	add_column :culturas, :p83_c, :string
	add_column :culturas, :p83_d, :string
	add_column :culturas, :p83_e, :string
	add_column :culturas, :p83_f, :string
	add_column :culturas, :p83_g, :string
	add_column :culturas, :p83_h, :string
	add_column :culturas, :p83_i, :string
	add_column :culturas, :p83_j, :string
	add_column :culturas, :p84_a, :string
	add_column :culturas, :p84_b, :string
	add_column :culturas, :p84_c, :string
	add_column :culturas, :p84_d, :string
	add_column :culturas, :p84_e, :string
	add_column :culturas, :p84_f, :string
	add_column :culturas, :p84_g, :string
	add_column :culturas, :p84_h, :string
	add_column :culturas, :p84_i, :string
	add_column :culturas, :p84_j, :string
	add_column :culturas, :p85, :string
	add_column :culturas, :p86, :string
	add_column :culturas, :p87_a, :string
	add_column :culturas, :p87_b, :string
	add_column :culturas, :p87_c, :string
	add_column :culturas, :p87_d, :string
	add_column :culturas, :p87_e, :string
	add_column :culturas, :p87_f, :string
	add_column :culturas, :p87_g, :string
	add_column :culturas, :p87_h, :string
	add_column :culturas, :p87_i, :string
	add_column :culturas, :p87_j, :string
	add_column :culturas, :p88, :string
	add_column :culturas, :p89, :string
	add_column :culturas, :p90, :string
	add_column :culturas, :p91, :string
	add_column :culturas, :p92, :string
	add_column :culturas, :p93, :string
	add_column :culturas, :p94, :string
	add_column :culturas, :p95, :string
	add_column :culturas, :p96_a, :string
	add_column :culturas, :p96_b, :string
	add_column :culturas, :p96_c, :string
	add_column :culturas, :p96_d, :string
	add_column :culturas, :p97_a, :string
	add_column :culturas, :p97_b, :string
	add_column :culturas, :p97_c, :string
	add_column :culturas, :p97_d, :string
	add_column :culturas, :p97_e, :string
	add_column :culturas, :p97_f, :string
	add_column :culturas, :p97_g, :string
	add_column :culturas, :p98, :string
	add_column :culturas, :p99, :string
	add_column :culturas, :p100, :string
	add_column :culturas, :p101, :string
	add_column :culturas, :p102_a, :string
	add_column :culturas, :p102_b, :string
	add_column :culturas, :p102_c, :string
	add_column :culturas, :p102_d, :string
	add_column :culturas, :p102_e, :string
	add_column :culturas, :p102_f, :string
	add_column :culturas, :p102_g, :string
	add_column :culturas, :p102_h, :string
	add_column :culturas, :p102_i, :string
	add_column :culturas, :p103, :string
	add_column :culturas, :p104, :string
	add_column :culturas, :p105, :string
	add_column :culturas, :p106, :string
	add_column :culturas, :p107, :string
	add_column :culturas, :p108, :string
	add_column :culturas, :p109, :string
	add_column :culturas, :p110, :string
	add_column :culturas, :p111, :string
	add_column :culturas, :p112, :string
	add_column :culturas, :p113, :string
	add_column :culturas, :p114, :string
	add_column :culturas, :p115_a, :string
	add_column :culturas, :p115_b, :string
	add_column :culturas, :p115_c, :string
	add_column :culturas, :p115_d, :string
	add_column :culturas, :p115_e, :string
	add_column :culturas, :p115_f, :string
	add_column :culturas, :p115_g, :string
	add_column :culturas, :p115_h, :string
	add_column :culturas, :p115_i, :string
	add_column :culturas, :p116, :string
	add_column :culturas, :p117, :string
	add_column :culturas, :p118, :string
	add_column :culturas, :p119, :string
	add_column :culturas, :p120, :string
	add_column :culturas, :p121, :string
	add_column :culturas, :p122, :string
	add_column :culturas, :p122_a, :string
	add_column :culturas, :p123, :string
	add_column :culturas, :p124, :string
	add_column :culturas, :p125, :string
	add_column :culturas, :p126, :string
	add_column :culturas, :p127, :string
	add_column :culturas, :p128, :string
	add_column :culturas, :p129, :string

  end
end
