class AddCultura1 < ActiveRecord::Migration[5.2]
  def change

  	add_column :cultura1s, :pa, :string
add_column :cultura1s, :p8, :string
add_column :cultura1s, :p9, :string
add_column :cultura1s, :p10, :string
add_column :cultura1s, :p11, :string
add_column :cultura1s, :p12, :string
add_column :cultura1s, :p13, :string
add_column :cultura1s, :p14_a, :string
add_column :cultura1s, :p14_b, :string
add_column :cultura1s, :p14_c, :string
add_column :cultura1s, :p14_d, :string
add_column :cultura1s, :p14_e, :string
add_column :cultura1s, :p14_f, :string
add_column :cultura1s, :p15, :string
add_column :cultura1s, :p16_a, :string
add_column :cultura1s, :p16_b, :string
add_column :cultura1s, :p16_c, :string
add_column :cultura1s, :p16_d, :string
add_column :cultura1s, :p16_e, :string
add_column :cultura1s, :p17_a, :string
add_column :cultura1s, :p17_b, :string
add_column :cultura1s, :p17_c, :string
add_column :cultura1s, :p17_d, :string
add_column :cultura1s, :p17_e, :string
add_column :cultura1s, :p17_f, :string
add_column :cultura1s, :p17_g, :string
add_column :cultura1s, :p18_a, :string
add_column :cultura1s, :p18_b, :string
add_column :cultura1s, :p18_c, :string
add_column :cultura1s, :p18_d, :string
add_column :cultura1s, :p18_e, :string
add_column :cultura1s, :p18_f, :string
add_column :cultura1s, :p18_g, :string
add_column :cultura1s, :p18_h, :string
add_column :cultura1s, :p18_i, :string
add_column :cultura1s, :p18_j, :string
add_column :cultura1s, :p18_k, :string
add_column :cultura1s, :p18_l, :string
add_column :cultura1s, :p18_m, :string
add_column :cultura1s, :p18_n, :string
add_column :cultura1s, :p18_z, :string
add_column :cultura1s, :p18_o, :string
add_column :cultura1s, :p18_p, :string
add_column :cultura1s, :p18_q, :string
add_column :cultura1s, :p19_a, :string
add_column :cultura1s, :p19_b, :string
add_column :cultura1s, :p19_c, :string
add_column :cultura1s, :p19_d, :string
add_column :cultura1s, :p19_e, :string
add_column :cultura1s, :p19_f, :string
add_column :cultura1s, :p19_g, :string
add_column :cultura1s, :p19_h, :string
add_column :cultura1s, :p20_a, :string
add_column :cultura1s, :p20_b, :string
add_column :cultura1s, :p20_c, :string
add_column :cultura1s, :p20_d, :string
add_column :cultura1s, :p20_e, :string
add_column :cultura1s, :p21_a, :string
add_column :cultura1s, :p21_b, :string
add_column :cultura1s, :p21_c, :string
add_column :cultura1s, :p21_d, :string
add_column :cultura1s, :p21_e, :string
add_column :cultura1s, :p22, :string
add_column :cultura1s, :p23_a, :string
add_column :cultura1s, :p23_b, :string
add_column :cultura1s, :p23_c, :string
add_column :cultura1s, :p24_a, :string
add_column :cultura1s, :p24_b, :string
add_column :cultura1s, :p25_a, :string
add_column :cultura1s, :p25_b, :string
add_column :cultura1s, :p25_c, :string
add_column :cultura1s, :p25_d, :string
add_column :cultura1s, :p25_e, :string
add_column :cultura1s, :p25_f, :string
add_column :cultura1s, :p26, :string
add_column :cultura1s, :p27_a, :string
add_column :cultura1s, :p27_b, :string
add_column :cultura1s, :p27_c, :string
add_column :cultura1s, :p27_d, :string
add_column :cultura1s, :p27_e, :string
add_column :cultura1s, :p27_f, :string
add_column :cultura1s, :p28_a, :string
add_column :cultura1s, :p28_b, :string
add_column :cultura1s, :p28_c, :string
add_column :cultura1s, :p28_d, :string
add_column :cultura1s, :p28_e, :string
add_column :cultura1s, :p28_f, :string
add_column :cultura1s, :p28_g, :string
add_column :cultura1s, :p28_h, :string
add_column :cultura1s, :p28_i, :string
add_column :cultura1s, :p28_j, :string
add_column :cultura1s, :p28_k, :string
add_column :cultura1s, :p29_a, :string
add_column :cultura1s, :p29_b, :string
add_column :cultura1s, :p29_c, :string
add_column :cultura1s, :p29_d, :string
add_column :cultura1s, :p30, :string
add_column :cultura1s, :p31_a, :string
add_column :cultura1s, :p31_b, :string
add_column :cultura1s, :p31_c, :string
add_column :cultura1s, :p31_d, :string
add_column :cultura1s, :p31_e, :string
add_column :cultura1s, :p32, :string
add_column :cultura1s, :p33, :string
add_column :cultura1s, :p34_a, :string
add_column :cultura1s, :p34_b, :string
add_column :cultura1s, :p34_c, :string
add_column :cultura1s, :p34_d, :string
add_column :cultura1s, :p34_e, :string
add_column :cultura1s, :p34_f, :string
add_column :cultura1s, :p34_g, :string
add_column :cultura1s, :p34_h, :string
add_column :cultura1s, :p35, :string
add_column :cultura1s, :p36, :string
add_column :cultura1s, :p37_a, :string
add_column :cultura1s, :p37_b, :string
add_column :cultura1s, :p37_c, :string
add_column :cultura1s, :p37_d, :string
add_column :cultura1s, :p37_e, :string
add_column :cultura1s, :p37_f, :string
add_column :cultura1s, :p37_g, :string
add_column :cultura1s, :p37_h, :string
add_column :cultura1s, :p37_i, :string
add_column :cultura1s, :p37_j, :string
add_column :cultura1s, :p37_k, :string
add_column :cultura1s, :p37_l, :string
add_column :cultura1s, :p38_a, :string
add_column :cultura1s, :p38_b, :string
add_column :cultura1s, :p38_c, :string
add_column :cultura1s, :p38_d, :string
add_column :cultura1s, :p38_e, :string
add_column :cultura1s, :p38_f, :string
add_column :cultura1s, :p39_a, :string
add_column :cultura1s, :p39_b, :string
add_column :cultura1s, :p39_c, :string
add_column :cultura1s, :p39_d, :string
add_column :cultura1s, :p39_e, :string
add_column :cultura1s, :p39_f, :string
add_column :cultura1s, :p39_g, :string
add_column :cultura1s, :p40, :string
add_column :cultura1s, :p41_a, :string
add_column :cultura1s, :p41_b, :string
add_column :cultura1s, :p41_c, :string
add_column :cultura1s, :p41_d, :string
add_column :cultura1s, :p41_e, :string
add_column :cultura1s, :p42_a, :string
add_column :cultura1s, :p42_b, :string
add_column :cultura1s, :p42_c, :string
add_column :cultura1s, :p42_d, :string
add_column :cultura1s, :p42_e, :string
add_column :cultura1s, :p42_f, :string
add_column :cultura1s, :p42_g, :string
add_column :cultura1s, :p42_h, :string
add_column :cultura1s, :p42_i, :string
add_column :cultura1s, :p42_j, :string
add_column :cultura1s, :p42_k, :string
add_column :cultura1s, :p42_l, :string
add_column :cultura1s, :p42_m, :string
add_column :cultura1s, :p43, :string
add_column :cultura1s, :p44, :string
add_column :cultura1s, :p44o, :string
add_column :cultura1s, :p45_a, :string
add_column :cultura1s, :p45_b, :string
add_column :cultura1s, :p45_c, :string
add_column :cultura1s, :p45_d, :string
add_column :cultura1s, :p45_e, :string
add_column :cultura1s, :p46_a, :string
add_column :cultura1s, :p46_b, :string
add_column :cultura1s, :p46_c, :string
add_column :cultura1s, :p46_d, :string
add_column :cultura1s, :p46_e, :string
add_column :cultura1s, :p47, :string
add_column :cultura1s, :p48_a, :string
add_column :cultura1s, :p48_b, :string
add_column :cultura1s, :p48_c, :string
add_column :cultura1s, :p48_d, :string
add_column :cultura1s, :p48_e, :string
add_column :cultura1s, :p48_f, :string
add_column :cultura1s, :p48_g, :string
add_column :cultura1s, :p49, :string
add_column :cultura1s, :p50, :string
add_column :cultura1s, :p50o, :string
add_column :cultura1s, :p51, :string
add_column :cultura1s, :p52_1, :string
add_column :cultura1s, :p52_2, :string
add_column :cultura1s, :p52_3, :string
add_column :cultura1s, :p52_4, :string
add_column :cultura1s, :p53, :string
add_column :cultura1s, :p54, :string
add_column :cultura1s, :p54o, :string
add_column :cultura1s, :p55_a, :string
add_column :cultura1s, :p55_b, :string
add_column :cultura1s, :p55_c, :string
add_column :cultura1s, :p55_d, :string
add_column :cultura1s, :p56_1, :string
add_column :cultura1s, :p56_2, :string
add_column :cultura1s, :p56_3, :string
add_column :cultura1s, :p56_4, :string
add_column :cultura1s, :p56_5, :string
add_column :cultura1s, :p56_6, :string
add_column :cultura1s, :p56_7, :string
add_column :cultura1s, :p57_a, :string
add_column :cultura1s, :p57_b, :string
add_column :cultura1s, :p57_c, :string
add_column :cultura1s, :p57_d, :string
add_column :cultura1s, :p58_a, :string
add_column :cultura1s, :p58_b, :string
add_column :cultura1s, :p58_c, :string
add_column :cultura1s, :p58_d, :string
add_column :cultura1s, :p58_e, :string
add_column :cultura1s, :p59, :string
add_column :cultura1s, :p60_a, :string
add_column :cultura1s, :p60_b, :string
add_column :cultura1s, :p60_c, :string
add_column :cultura1s, :p60_d, :string
add_column :cultura1s, :p60_e, :string
add_column :cultura1s, :p60_f, :string
add_column :cultura1s, :p60_g, :string
add_column :cultura1s, :p60_h, :string
add_column :cultura1s, :p60_i, :string
add_column :cultura1s, :p60_j, :string
add_column :cultura1s, :p60_k, :string
add_column :cultura1s, :p60_l, :string
add_column :cultura1s, :p60_m, :string
add_column :cultura1s, :p61, :string
add_column :cultura1s, :p62_a, :string
add_column :cultura1s, :p62_b, :string
add_column :cultura1s, :p62_c, :string
add_column :cultura1s, :p62_d, :string
add_column :cultura1s, :p62_e, :string
add_column :cultura1s, :p63_a, :string
add_column :cultura1s, :p63_b, :string
add_column :cultura1s, :p63_c, :string
add_column :cultura1s, :p63_d, :string
add_column :cultura1s, :p64, :string
add_column :cultura1s, :p65_a, :string
add_column :cultura1s, :p65_b, :string
add_column :cultura1s, :p65_c, :string
add_column :cultura1s, :p65_d, :string
add_column :cultura1s, :p65_e, :string
add_column :cultura1s, :p65_f, :string
add_column :cultura1s, :p65_g, :string
add_column :cultura1s, :p65_h, :string
add_column :cultura1s, :p65_i, :string
add_column :cultura1s, :p65_j, :string
add_column :cultura1s, :p66, :string
add_column :cultura1s, :p67, :string
add_column :cultura1s, :p67o, :string
add_column :cultura1s, :p68_1, :string
add_column :cultura1s, :p68_2, :string
add_column :cultura1s, :p68_3, :string
add_column :cultura1s, :p68_4, :string
add_column :cultura1s, :p68_5, :string
add_column :cultura1s, :p68_6, :string
add_column :cultura1s, :p68_7, :string
add_column :cultura1s, :p68_8, :string
add_column :cultura1s, :p68_9, :string
add_column :cultura1s, :p68_10, :string
add_column :cultura1s, :p69_a, :string
add_column :cultura1s, :p69_b, :string
add_column :cultura1s, :p69_c, :string
add_column :cultura1s, :p70_a, :string
add_column :cultura1s, :p70_b, :string
add_column :cultura1s, :p70_c, :string
add_column :cultura1s, :p71, :string
add_column :cultura1s, :p72, :string
add_column :cultura1s, :p73, :string
add_column :cultura1s, :p74, :string
add_column :cultura1s, :p75, :string
add_column :cultura1s, :p76_a, :string
add_column :cultura1s, :p76_b, :string
add_column :cultura1s, :p76_c, :string
add_column :cultura1s, :p76_d, :string
add_column :cultura1s, :p76_e, :string
add_column :cultura1s, :p76_f, :string
add_column :cultura1s, :p76_g, :string
add_column :cultura1s, :p77, :string
add_column :cultura1s, :p78, :string
add_column :cultura1s, :p79, :string
add_column :cultura1s, :p80, :string
add_column :cultura1s, :p80o, :string
add_column :cultura1s, :p81_a, :string
add_column :cultura1s, :p81_b, :string
add_column :cultura1s, :p81_c, :string
add_column :cultura1s, :p81_d, :string
add_column :cultura1s, :p81_e, :string
add_column :cultura1s, :p82, :string
add_column :cultura1s, :p82o, :string
add_column :cultura1s, :p83_a, :string
add_column :cultura1s, :p83_b, :string
add_column :cultura1s, :p83_c, :string
add_column :cultura1s, :p83_d, :string
add_column :cultura1s, :p83_e, :string
add_column :cultura1s, :p83_f, :string
add_column :cultura1s, :p83_g, :string
add_column :cultura1s, :p83_h, :string
add_column :cultura1s, :p83_i, :string
add_column :cultura1s, :p83_j, :string
add_column :cultura1s, :p84_a, :string
add_column :cultura1s, :p84_b, :string
add_column :cultura1s, :p84_c, :string
add_column :cultura1s, :p84_d, :string
add_column :cultura1s, :p84_e, :string
add_column :cultura1s, :p84_f, :string
add_column :cultura1s, :p84_g, :string
add_column :cultura1s, :p84_h, :string
add_column :cultura1s, :p84_i, :string
add_column :cultura1s, :p84_j, :string
add_column :cultura1s, :p85, :string
add_column :cultura1s, :p86, :string
add_column :cultura1s, :p87_a, :string
add_column :cultura1s, :p87_b, :string
add_column :cultura1s, :p87_c, :string
add_column :cultura1s, :p87_d, :string
add_column :cultura1s, :p87_e, :string
add_column :cultura1s, :p87_f, :string
add_column :cultura1s, :p87_g, :string
add_column :cultura1s, :p87_h, :string
add_column :cultura1s, :p87_i, :string
add_column :cultura1s, :p87_j, :string
add_column :cultura1s, :p88, :string
add_column :cultura1s, :p89, :string
add_column :cultura1s, :p90, :string
add_column :cultura1s, :p90o, :string
add_column :cultura1s, :p91, :string
add_column :cultura1s, :p92, :string
add_column :cultura1s, :p93, :string
add_column :cultura1s, :p93o, :string
add_column :cultura1s, :p94, :string
add_column :cultura1s, :p95, :string
add_column :cultura1s, :p96_a, :string
add_column :cultura1s, :p96_b, :string
add_column :cultura1s, :p96_c, :string
add_column :cultura1s, :p96_d, :string
add_column :cultura1s, :p97_a, :string
add_column :cultura1s, :p97_b, :string
add_column :cultura1s, :p97_c, :string
add_column :cultura1s, :p97_d, :string
add_column :cultura1s, :p97_e, :string
add_column :cultura1s, :p97_f, :string
add_column :cultura1s, :p97_g, :string
add_column :cultura1s, :p98, :string
add_column :cultura1s, :p99, :string
add_column :cultura1s, :p100, :string
add_column :cultura1s, :p101_1, :string
add_column :cultura1s, :p101_2, :string
add_column :cultura1s, :p101_3, :string
add_column :cultura1s, :p101_4, :string
add_column :cultura1s, :p101_5, :string
add_column :cultura1s, :p101_6, :string
add_column :cultura1s, :p101_7, :string
add_column :cultura1s, :p101_8, :string
add_column :cultura1s, :p101_9, :string
add_column :cultura1s, :p101_10, :string
add_column :cultura1s, :p101_11, :string
add_column :cultura1s, :p101_12, :string
add_column :cultura1s, :p101_13, :string
add_column :cultura1s, :p101_14, :string
add_column :cultura1s, :p101_15, :string
add_column :cultura1s, :p101_16, :string
add_column :cultura1s, :p101_17, :string
add_column :cultura1s, :p101_18, :string
add_column :cultura1s, :p101_19, :string
add_column :cultura1s, :p101_20, :string
add_column :cultura1s, :p101_21, :string
add_column :cultura1s, :p102_a_1, :string
add_column :cultura1s, :p102_a_2, :string
add_column :cultura1s, :p102_a_3, :string
add_column :cultura1s, :p102_b_1, :string
add_column :cultura1s, :p102_b_2, :string
add_column :cultura1s, :p102_b_3, :string
add_column :cultura1s, :p102_c_1, :string
add_column :cultura1s, :p102_c_2, :string
add_column :cultura1s, :p102_c_3, :string
add_column :cultura1s, :p102_d_1, :string
add_column :cultura1s, :p102_d_2, :string
add_column :cultura1s, :p102_d_3, :string
add_column :cultura1s, :p102_e_1, :string
add_column :cultura1s, :p102_e_2, :string
add_column :cultura1s, :p102_e_3, :string
add_column :cultura1s, :p102_f_1, :string
add_column :cultura1s, :p102_f_2, :string
add_column :cultura1s, :p102_f_3, :string
add_column :cultura1s, :p102_g_1, :string
add_column :cultura1s, :p102_g_2, :string
add_column :cultura1s, :p102_g_3, :string
add_column :cultura1s, :p102_h_1, :string
add_column :cultura1s, :p102_h_2, :string
add_column :cultura1s, :p102_h_3, :string
add_column :cultura1s, :p102i, :string
add_column :cultura1s, :p102_i_1, :string
add_column :cultura1s, :p102_i_2, :string
add_column :cultura1s, :p102_i_3, :string
add_column :cultura1s, :p103, :string
add_column :cultura1s, :p104, :string
add_column :cultura1s, :p105, :string
add_column :cultura1s, :p106, :string
add_column :cultura1s, :p106o, :string
add_column :cultura1s, :p107, :string
add_column :cultura1s, :p107o, :string
add_column :cultura1s, :p108, :string
add_column :cultura1s, :p109, :string
add_column :cultura1s, :p110, :string
add_column :cultura1s, :p110o, :string
add_column :cultura1s, :p111, :string
add_column :cultura1s, :p112, :string
add_column :cultura1s, :p113, :string
add_column :cultura1s, :p114, :string
add_column :cultura1s, :p115_a, :string
add_column :cultura1s, :p115_b, :string
add_column :cultura1s, :p115_c, :string
add_column :cultura1s, :p115_d, :string
add_column :cultura1s, :p115_e, :string
add_column :cultura1s, :p115_f, :string
add_column :cultura1s, :p115_g, :string
add_column :cultura1s, :p115_h, :string
add_column :cultura1s, :p115_i, :string
add_column :cultura1s, :p116_1, :string
add_column :cultura1s, :p116_2, :string
add_column :cultura1s, :p116_3, :string
add_column :cultura1s, :p116_4, :string
add_column :cultura1s, :p116_5, :string
add_column :cultura1s, :p116_6, :string
add_column :cultura1s, :p116_7, :string
add_column :cultura1s, :p116_8, :string
add_column :cultura1s, :p116_9, :string
add_column :cultura1s, :p116_10, :string
add_column :cultura1s, :p116_11, :string
add_column :cultura1s, :p116_12, :string
add_column :cultura1s, :p117, :string
add_column :cultura1s, :p118, :string
add_column :cultura1s, :p119, :string
add_column :cultura1s, :p120, :string
add_column :cultura1s, :p121, :string
add_column :cultura1s, :p122, :string
add_column :cultura1s, :p122_a, :string
add_column :cultura1s, :p123, :string
add_column :cultura1s, :p124, :string
add_column :cultura1s, :p125, :string
add_column :cultura1s, :p125o, :string
add_column :cultura1s, :p126, :string
add_column :cultura1s, :p127, :string
add_column :cultura1s, :p128_1, :string
add_column :cultura1s, :p128_2, :string
add_column :cultura1s, :p128_3, :string
add_column :cultura1s, :p128_4, :string
add_column :cultura1s, :p128_5, :string
add_column :cultura1s, :p128_6, :string
add_column :cultura1s, :p128_7, :string
add_column :cultura1s, :p128_8, :string
add_column :cultura1s, :p128_9, :string
add_column :cultura1s, :p128_10, :string
add_column :cultura1s, :p128_11, :string
add_column :cultura1s, :p128o, :string
add_column :cultura1s, :p129_1, :string
add_column :cultura1s, :p129_2, :string
add_column :cultura1s, :p129_3, :string
add_column :cultura1s, :p129_4, :string
add_column :cultura1s, :p129_5, :string
add_column :cultura1s, :p129_6, :string
add_column :cultura1s, :p129_7, :string
add_column :cultura1s, :p129_8, :string
add_column :cultura1s, :p129_9, :string
add_column :cultura1s, :p129_10, :string
add_column :cultura1s, :p129_11, :string
add_column :cultura1s, :p129_12, :string
add_column :cultura1s, :m1_p1, :string
add_column :cultura1s, :m1_p2, :string
add_column :cultura1s, :m1_p3_1, :string
add_column :cultura1s, :m1_p3_2, :string
add_column :cultura1s, :m1_p3_3, :string
add_column :cultura1s, :m1_p3_4, :string
add_column :cultura1s, :m1_p3_5, :string
add_column :cultura1s, :m1_p3_6, :string
add_column :cultura1s, :m1_p3_7, :string
add_column :cultura1s, :m1_p3_8, :string
add_column :cultura1s, :m1_p4, :string
add_column :cultura1s, :m1_p5, :string
add_column :cultura1s, :m1_p5o, :string
add_column :cultura1s, :m1_p6_1, :string
add_column :cultura1s, :m1_p6_2, :string
add_column :cultura1s, :m1_p6_3, :string
add_column :cultura1s, :m1_p6_4, :string
add_column :cultura1s, :m1_p6_5, :string
add_column :cultura1s, :m1_p6_6, :string
add_column :cultura1s, :m1_p7, :string
add_column :cultura1s, :m1_p7o, :string
add_column :cultura1s, :m1_p8_1, :string
add_column :cultura1s, :m1_p8_2, :string
add_column :cultura1s, :m1_p8_3, :string
add_column :cultura1s, :m1_p8_4, :string
add_column :cultura1s, :m1_p8_5, :string
add_column :cultura1s, :m1_p9_1, :string
add_column :cultura1s, :m1_p9_2, :string
add_column :cultura1s, :m1_p9_3, :string
add_column :cultura1s, :m1_p9_4, :string
add_column :cultura1s, :m1_p9_5, :string
add_column :cultura1s, :m1_p10, :string
add_column :cultura1s, :m1_p11, :string
add_column :cultura1s, :m1_p12_1, :string
add_column :cultura1s, :m1_p12_2, :string
add_column :cultura1s, :m1_p12_3, :string
add_column :cultura1s, :m1_p12_4, :string
add_column :cultura1s, :m1_p12_5, :string
add_column :cultura1s, :m1_p12_6, :string
add_column :cultura1s, :m1_p12_7, :string
add_column :cultura1s, :m1_p12_8, :string
add_column :cultura1s, :m1_p12_7o, :string
add_column :cultura1s, :m2_p1, :string
add_column :cultura1s, :m2_p2_1, :string
add_column :cultura1s, :m2_p2_2, :string
add_column :cultura1s, :m2_p2_3, :string
add_column :cultura1s, :m2_p2_4, :string
add_column :cultura1s, :m2_p3, :string
add_column :cultura1s, :m2_p4, :string
add_column :cultura1s, :m2_p4o, :string
add_column :cultura1s, :m2_p5_1, :string
add_column :cultura1s, :m2_p5_2, :string
add_column :cultura1s, :m2_p5_3, :string
add_column :cultura1s, :m2_p5_4, :string
add_column :cultura1s, :m2_p5_5, :string
add_column :cultura1s, :m2_p5_6, :string
add_column :cultura1s, :m2_p6, :string
add_column :cultura1s, :m2_p7, :string
add_column :cultura1s, :m2_p8, :string
add_column :cultura1s, :m2_p8_1, :string
add_column :cultura1s, :m2_p9, :string
add_column :cultura1s, :m2_p10, :string
add_column :cultura1s, :m2_p11, :string
add_column :cultura1s, :m2_p12, :string
add_column :cultura1s, :m2_p13, :string
add_column :cultura1s, :m2_p14, :string
add_column :cultura1s, :m2_p15, :string
add_column :cultura1s, :m2_p16_1, :string
add_column :cultura1s, :m2_p16_2, :string
add_column :cultura1s, :m2_p16_3, :string
add_column :cultura1s, :m2_p16_4, :string
add_column :cultura1s, :m2_p16_5, :string
add_column :cultura1s, :m2_p16_6, :string
add_column :cultura1s, :m2_p16_7, :string
add_column :cultura1s, :m2_p16_8, :string
add_column :cultura1s, :m2_p17, :string
add_column :cultura1s, :m3_p1_1, :string
add_column :cultura1s, :m3_p1_2, :string
add_column :cultura1s, :m3_p1_3, :string
add_column :cultura1s, :m3_p1_4, :string
add_column :cultura1s, :m3_p1_5, :string
add_column :cultura1s, :m3_p2_1, :string
add_column :cultura1s, :m3_p2_2, :string
add_column :cultura1s, :m3_p2_3, :string
add_column :cultura1s, :m3_p2_4, :string
add_column :cultura1s, :m3_p2_5, :string
add_column :cultura1s, :m3_p2_6, :string
add_column :cultura1s, :m3_p2_7, :string
add_column :cultura1s, :m3_p2_8, :string
add_column :cultura1s, :m3_p2_9, :string
add_column :cultura1s, :m3_p2_10, :string
add_column :cultura1s, :m3_p2_11, :string
add_column :cultura1s, :m3_p3_1, :string
add_column :cultura1s, :m3_p3_2, :string
add_column :cultura1s, :m3_p3_3, :string
add_column :cultura1s, :m3_p3_4, :string
add_column :cultura1s, :m3_p3_5, :string
add_column :cultura1s, :m3_p3_6, :string
add_column :cultura1s, :m3_p3_7, :string
add_column :cultura1s, :m3_p3_8, :string
add_column :cultura1s, :m3_p3_9, :string
add_column :cultura1s, :m3_p4_1, :string
add_column :cultura1s, :m3_p4_2, :string
add_column :cultura1s, :m3_p4_3, :string
add_column :cultura1s, :m3_p4_4, :string
add_column :cultura1s, :m3_p5, :string
add_column :cultura1s, :m3_p6, :string
add_column :cultura1s, :m3_p7, :string
add_column :cultura1s, :m3_p8, :string
add_column :cultura1s, :m3_p9, :string
add_column :cultura1s, :m3_p10, :string
add_column :cultura1s, :m3_p11, :string
add_column :cultura1s, :m4_p1a_1, :string
add_column :cultura1s, :m4_p1a_2, :string
add_column :cultura1s, :m4_p1a_3, :string
add_column :cultura1s, :m4_p1a_4, :string
add_column :cultura1s, :m4_p1a_5, :string
add_column :cultura1s, :m4_p1a_6, :string
add_column :cultura1s, :m4_p1a_7, :string
add_column :cultura1s, :m4_p1b_1, :string
add_column :cultura1s, :m4_p1b_2, :string
add_column :cultura1s, :m4_p1b_3, :string
add_column :cultura1s, :m4_p1b_4, :string
add_column :cultura1s, :m4_p1b_5, :string
add_column :cultura1s, :m4_p1b_6, :string
add_column :cultura1s, :m4_p1b_7, :string
add_column :cultura1s, :m4_p1c_1, :string
add_column :cultura1s, :m4_p1c_2, :string
add_column :cultura1s, :m4_p1c_3, :string
add_column :cultura1s, :m4_p1c_4, :string
add_column :cultura1s, :m4_p1c_5, :string
add_column :cultura1s, :m4_p1c_6, :string
add_column :cultura1s, :m4_p1c_7, :string
add_column :cultura1s, :m4_p1d_1, :string
add_column :cultura1s, :m4_p1d_2, :string
add_column :cultura1s, :m4_p1d_3, :string
add_column :cultura1s, :m4_p1d_4, :string
add_column :cultura1s, :m4_p1d_5, :string
add_column :cultura1s, :m4_p1d_6, :string
add_column :cultura1s, :m4_p1d_7, :string
add_column :cultura1s, :m4_p2_1, :string
add_column :cultura1s, :m4_p2_2, :string
add_column :cultura1s, :m4_p2_3, :string
add_column :cultura1s, :m4_p2_4, :string
add_column :cultura1s, :m4_p3_1, :string
add_column :cultura1s, :m4_p3_2, :string
add_column :cultura1s, :m4_p3_3, :string
add_column :cultura1s, :m4_p3_4, :string
add_column :cultura1s, :m4_p3_5, :string
add_column :cultura1s, :m4_p4_1, :string
add_column :cultura1s, :m4_p4_2, :string
add_column :cultura1s, :m4_p4_3, :string
add_column :cultura1s, :m4_p4_4, :string
add_column :cultura1s, :m4_p4_5, :string
add_column :cultura1s, :m4_p4_6, :string
add_column :cultura1s, :m4_p4_7, :string
add_column :cultura1s, :m4_p4_8, :string
add_column :cultura1s, :m4_p4_9, :string
add_column :cultura1s, :m4_p4_10, :string
add_column :cultura1s, :m4_p5_1, :string
add_column :cultura1s, :m4_p5_2, :string
add_column :cultura1s, :m4_p5_3, :string
add_column :cultura1s, :m4_p5_4, :string
add_column :cultura1s, :m4_p5_5, :string
add_column :cultura1s, :m4_p6, :string
add_column :cultura1s, :m4_p7_1, :string
add_column :cultura1s, :m4_p7_2, :string
add_column :cultura1s, :m4_p7_3, :string
add_column :cultura1s, :m4_p7_4, :string
add_column :cultura1s, :m4_p7_5, :string

  end
end
