class AddEstudiantesP12aP19 < ActiveRecord::Migration[5.2]
  def change
  	add_column :estudiantes, :p12a_1, :string
  	add_column :estudiantes, :p12a_2, :string
  	add_column :estudiantes, :p12a_3, :string
  	add_column :estudiantes, :p12a_4, :string
  	add_column :estudiantes, :p12b_1, :string
  	add_column :estudiantes, :p12b_2, :string
  	add_column :estudiantes, :p12b_3, :string
  	add_column :estudiantes, :p12b_4, :string
  	add_column :estudiantes, :p12c_1, :string
  	add_column :estudiantes, :p12c_2, :string
  	add_column :estudiantes, :p12c_3, :string
  	add_column :estudiantes, :p12c_4, :string
  	add_column :estudiantes, :p12d_1, :string
  	add_column :estudiantes, :p12d_2, :string
  	add_column :estudiantes, :p12d_3, :string
  	add_column :estudiantes, :p12d_4, :string
  	add_column :estudiantes, :p12e, :string
  	add_column :estudiantes, :p12f, :string
  	add_column :estudiantes, :p12g, :string
  	add_column :estudiantes, :p12h, :string
  	add_column :estudiantes, :p12i, :string
  	add_column :estudiantes, :p12j, :string
  	add_column :estudiantes, :p12k, :string
  	add_column :estudiantes, :p12l, :string
  	add_column :estudiantes, :p12m, :string
  	add_column :estudiantes, :p12n, :string
  	add_column :estudiantes, :p12o, :string
  	add_column :estudiantes, :p12o_1, :string
  	add_column :estudiantes, :p12p, :string
  	add_column :estudiantes, :p12pm_1, :string
  	add_column :estudiantes, :p12pm_2, :string
  	add_column :estudiantes, :p12pm_3, :string
  	add_column :estudiantes, :p12pm_4, :string
  	add_column :estudiantes, :p12pm_5, :string
  	add_column :estudiantes, :p12pm_6, :string
  	add_column :estudiantes, :p12pm_7, :string
  	add_column :estudiantes, :p12pm_8, :string
  	add_column :estudiantes, :p12pm_9, :string
  	add_column :estudiantes, :p12pm_10, :string
  	add_column :estudiantes, :p12q, :string
  	add_column :estudiantes, :p12q_1, :string
  	add_column :estudiantes, :p13a, :string
  	add_column :estudiantes, :p13b, :string
  	add_column :estudiantes, :p13c, :string
  	add_column :estudiantes, :p13d, :string
  	add_column :estudiantes, :p13e, :string
  	add_column :estudiantes, :p13f, :string
  	add_column :estudiantes, :p13g, :string
  	add_column :estudiantes, :p14a, :string
  	add_column :estudiantes, :p14b, :string
  	add_column :estudiantes, :p14c, :string
  	add_column :estudiantes, :p14d, :string
  	add_column :estudiantes, :p14e, :string
  	add_column :estudiantes, :p14f, :string
  	add_column :estudiantes, :p14g, :string
  	add_column :estudiantes, :p14h, :string
  	add_column :estudiantes, :p14i, :string
  	add_column :estudiantes, :p15a, :string
  	add_column :estudiantes, :p15b, :string
  	add_column :estudiantes, :p15c, :string
  	add_column :estudiantes, :p15d, :string
  	add_column :estudiantes, :p15e, :string
  	add_column :estudiantes, :p15f, :string
  	add_column :estudiantes, :p16a, :string
  	add_column :estudiantes, :p16b, :string
  	add_column :estudiantes, :p16c, :string
  	add_column :estudiantes, :p16d, :string
  	add_column :estudiantes, :p16e, :string
  	add_column :estudiantes, :p16f, :string
  	add_column :estudiantes, :p16g, :string
  	add_column :estudiantes, :p17, :string
  	add_column :estudiantes, :p17a_1, :string
  	add_column :estudiantes, :p17a_2, :string
  	add_column :estudiantes, :p17a_3, :string
  	add_column :estudiantes, :p17a_4, :string
  	add_column :estudiantes, :p17b_1, :string
  	add_column :estudiantes, :p17b_2, :string
  	add_column :estudiantes, :p17b_3, :string
  	add_column :estudiantes, :p17b_4, :string
  	add_column :estudiantes, :p17c_1, :string
  	add_column :estudiantes, :p17c_2, :string
  	add_column :estudiantes, :p17c_3, :string
  	add_column :estudiantes, :p17c_4, :string
  	add_column :estudiantes, :p18, :string
  	add_column :estudiantes, :p19, :string

  end
end
