class AddColumnstoDirectors1 < ActiveRecord::Migration[5.2]
  def change
  	add_column :directors, :p8_1_1, :string
  	add_column :directors, :p8_1_2, :string
  	add_column :directors, :p8_1_3, :string
  	add_column :directors, :p8_1_4, :string
  	add_column :directors, :p8_1_5, :string
  	add_column :directors, :p8_2_1, :string
  	add_column :directors, :p8_2_2, :string
  	add_column :directors, :p8_2_3, :string
  	add_column :directors, :p8_2_4, :string
  	add_column :directors, :p8_2_5, :string
  	add_column :directors, :p8_3_1, :string
  	add_column :directors, :p8_3_2, :string
  	add_column :directors, :p8_3_3, :string
  	add_column :directors, :p8_3_4, :string
  	add_column :directors, :p8_3_5, :string
  	add_column :directors, :p8_4_1, :string
  	add_column :directors, :p8_4_2, :string
  	add_column :directors, :p8_4_3, :string
  	add_column :directors, :p8_4_4, :string
  	add_column :directors, :p8_4_5, :string
  	add_column :directors, :p8_5_1, :string
  	add_column :directors, :p8_5_2, :string
  	add_column :directors, :p8_5_3, :string
  	add_column :directors, :p8_5_4, :string
  	add_column :directors, :p8_5_5, :string
  	add_column :directors, :p8_6_1, :string
  	add_column :directors, :p8_6_2, :string
  	add_column :directors, :p8_6_3, :string
  	add_column :directors, :p8_6_4, :string
  	add_column :directors, :p8_6_5, :string
  	add_column :directors, :p8_7_1, :string
  	add_column :directors, :p8_7_2, :string
  	add_column :directors, :p8_7_3, :string
  	add_column :directors, :p8_7_4, :string
  	add_column :directors, :p8_7_5, :string
  	add_column :directors, :p8_8_1, :string
  	add_column :directors, :p8_8_2, :string
  	add_column :directors, :p8_8_3, :string
  	add_column :directors, :p8_8_4, :string
  	add_column :directors, :p8_8_5, :string
  	add_column :directors, :p8_9_1, :string
  	add_column :directors, :p8_9_2, :string
  	add_column :directors, :p8_9_3, :string
  	add_column :directors, :p8_9_4, :string
  	add_column :directors, :p8_9_5, :string
  	add_column :directors, :p8_10_1, :string
  	add_column :directors, :p8_10_2, :string
  	add_column :directors, :p8_10_3, :string
  	add_column :directors, :p8_10_4, :string
  	add_column :directors, :p8_10_5, :string
  	add_column :directors, :p8_11_1, :string
  	add_column :directors, :p8_11_2, :string
  	add_column :directors, :p8_11_3, :string
  	add_column :directors, :p8_11_4, :string
  	add_column :directors, :p8_11_5, :string
  	add_column :directors, :p9, :string
  	add_column :directors, :p10, :string
  	add_column :directors, :p10_a_1, :string
  	add_column :directors, :p10_a_2, :string
  	add_column :directors, :p10_a_3, :string
  	add_column :directors, :p10_a_4, :string
  	add_column :directors, :p10_a_5, :string
  	add_column :directors, :p10a_otra, :string
  	add_column :directors, :p10b, :string
  end
end
