class AddEstudiantes3649 < ActiveRecord::Migration[5.2]
  def change
  	add_column :estudiantes, :p36a_1, :string
  	add_column :estudiantes, :p36a_2, :string
  	add_column :estudiantes, :p36a_3, :string
  	add_column :estudiantes, :p36a_4, :string
  	add_column :estudiantes, :p36a_5, :string
  	add_column :estudiantes, :p36a_6, :string
  	add_column :estudiantes, :p36a_7, :string
  	add_column :estudiantes, :p36a_8, :string
  	add_column :estudiantes, :p36a_9, :string
  	add_column :estudiantes, :p36a_10, :string
  	add_column :estudiantes, :p36a_11, :string
  	add_column :estudiantes, :p36a_12, :string
  	add_column :estudiantes, :p36a_13, :string
  	add_column :estudiantes, :p36ab, :string
  	add_column :estudiantes, :p37a, :string
  	add_column :estudiantes, :p37b, :string
  	add_column :estudiantes, :p37c, :string
  	add_column :estudiantes, :p37d, :string
  	add_column :estudiantes, :p37e, :string
  	add_column :estudiantes, :p38a, :string
  	add_column :estudiantes, :p38b, :string
  	add_column :estudiantes, :p38c, :string
  	add_column :estudiantes, :p38d, :string
  	add_column :estudiantes, :p39, :string
  	add_column :estudiantes, :p40_1, :string
  	add_column :estudiantes, :p40_2, :string
  	add_column :estudiantes, :p40_3, :string
  	add_column :estudiantes, :p40_4, :string
  	add_column :estudiantes, :p40_5, :string
  	add_column :estudiantes, :p40_6, :string
  	add_column :estudiantes, :p40_7, :string
  	add_column :estudiantes, :p41, :string
  	add_column :estudiantes, :p42, :string
  	add_column :estudiantes, :p43, :string
  	add_column :estudiantes, :p43a, :string
  	add_column :estudiantes, :p44b, :string
  	add_column :estudiantes, :p44c, :string
  	add_column :estudiantes, :p44d, :string
  	add_column :estudiantes, :p44e, :string
  	add_column :estudiantes, :p45a, :string
  	add_column :estudiantes, :p45b, :string
  	add_column :estudiantes, :p45c, :string
  	add_column :estudiantes, :p45d, :string
  	add_column :estudiantes, :p45e, :string
  	add_column :estudiantes, :p45f, :string
  	add_column :estudiantes, :p45g, :string
  	add_column :estudiantes, :p45h, :string
  	add_column :estudiantes, :p45i, :string
  	add_column :estudiantes, :p46_1, :string
  	add_column :estudiantes, :p46_2, :string
  	add_column :estudiantes, :p46_3, :string
  	add_column :estudiantes, :p46_4, :string
  	add_column :estudiantes, :p46_5, :string
  	add_column :estudiantes, :p46_6, :string
  	add_column :estudiantes, :p46_7, :string
  	add_column :estudiantes, :p46_8, :string
  	add_column :estudiantes, :p46a, :string
  	add_column :estudiantes, :p47, :string
  	add_column :estudiantes, :p47a, :string
  	add_column :estudiantes, :p47b, :string
  	add_column :estudiantes, :p48, :string
  	add_column :estudiantes, :p48a, :string
  	add_column :estudiantes, :p48b, :string
  	add_column :estudiantes, :p49, :string
  end
end
