class AbiertaAdd < ActiveRecord::Migration[5.2]
  def change

add_column :abierta, :pa, :string
add_column :abierta, :pb, :string
add_column :abierta, :supervisor, :string
add_column :abierta, :critico, :string
add_column :abierta, :digitador, :string
add_column :abierta, :fv_1, :string
add_column :abierta, :fv_2, :string
add_column :abierta, :fv_3, :string
add_column :abierta, :fa, :string
add_column :abierta, :hi, :string
add_column :abierta, :hf, :string
add_column :abierta, :pf, :string
add_column :abierta, :pg1, :string
add_column :abierta, :pg2, :string
add_column :abierta, :pg3, :string
add_column :abierta, :ph1, :string
add_column :abierta, :ph2, :string
add_column :abierta, :ph3, :string
add_column :abierta, :pi, :string
add_column :abierta, :p1, :string
add_column :abierta, :p2, :string
add_column :abierta, :p4a_1, :string
add_column :abierta, :p4a_2, :string
add_column :abierta, :p4a_3, :string
add_column :abierta, :p4a_4, :string
add_column :abierta, :p4a_5, :string
add_column :abierta, :p4a_6, :string
add_column :abierta, :p4a_7, :string
add_column :abierta, :p4a_8, :string
add_column :abierta, :p4b_1, :string
add_column :abierta, :p4b_2, :string
add_column :abierta, :p4b_3, :string
add_column :abierta, :p4b_4, :string
add_column :abierta, :p4b_5, :string
add_column :abierta, :p4b_6, :string
add_column :abierta, :p4b_7, :string
add_column :abierta, :p4b_8, :string
add_column :abierta, :p4c_1, :string
add_column :abierta, :p4c_2, :string
add_column :abierta, :p4c_3, :string
add_column :abierta, :p4c_4, :string
add_column :abierta, :p4c_5, :string
add_column :abierta, :p4c_6, :string
add_column :abierta, :p4c_7, :string
add_column :abierta, :p4c_8, :string
add_column :abierta, :p4d_1, :string
add_column :abierta, :p4d_2, :string
add_column :abierta, :p4d_3, :string
add_column :abierta, :p4d_4, :string
add_column :abierta, :p4d_5, :string
add_column :abierta, :p4d_6, :string
add_column :abierta, :p4d_7, :string
add_column :abierta, :p4d_8, :string
add_column :abierta, :p4e_1, :string
add_column :abierta, :p4e_2, :string
add_column :abierta, :p4e_3, :string
add_column :abierta, :p4e_4, :string
add_column :abierta, :p4e_5, :string
add_column :abierta, :p4e_6, :string
add_column :abierta, :p4e_7, :string
add_column :abierta, :p4e_8, :string
add_column :abierta, :p4f_1, :string
add_column :abierta, :p4f_2, :string
add_column :abierta, :p4f_3, :string
add_column :abierta, :p4f_4, :string
add_column :abierta, :p4f_5, :string
add_column :abierta, :p4f_6, :string
add_column :abierta, :p4f_7, :string
add_column :abierta, :p4f_8, :string
add_column :abierta, :p4g_1, :string
add_column :abierta, :p4g_2, :string
add_column :abierta, :p4g_3, :string
add_column :abierta, :p4g_4, :string
add_column :abierta, :p4g_5, :string
add_column :abierta, :p4g_6, :string
add_column :abierta, :p4g_7, :string
add_column :abierta, :p4g_8, :string
add_column :abierta, :p4h_1, :string
add_column :abierta, :p4h_2, :string
add_column :abierta, :p4h_3, :string
add_column :abierta, :p4h_4, :string
add_column :abierta, :p4h_5, :string
add_column :abierta, :p4h_6, :string
add_column :abierta, :p4h_7, :string
add_column :abierta, :p4h_8, :string
add_column :abierta, :p4i_1, :string
add_column :abierta, :p4i_2, :string
add_column :abierta, :p4i_3, :string
add_column :abierta, :p4i_4, :string
add_column :abierta, :p4i_5, :string
add_column :abierta, :p4i_6, :string
add_column :abierta, :p4i_7, :string
add_column :abierta, :p4i_8, :string
add_column :abierta, :p4j_1, :string
add_column :abierta, :p4j_2, :string
add_column :abierta, :p4j_3, :string
add_column :abierta, :p4j_4, :string
add_column :abierta, :p4j_5, :string
add_column :abierta, :p4j_6, :string
add_column :abierta, :p4j_7, :string
add_column :abierta, :p4j_8, :string
add_column :abierta, :p4k_1, :string
add_column :abierta, :p4k_2, :string
add_column :abierta, :p4k_3, :string
add_column :abierta, :p4k_4, :string
add_column :abierta, :p4k_5, :string
add_column :abierta, :p4k_6, :string
add_column :abierta, :p4k_7, :string
add_column :abierta, :p4k_8, :string
add_column :abierta, :p4l_1, :string
add_column :abierta, :p4l_2, :string
add_column :abierta, :p4l_3, :string
add_column :abierta, :p4l_4, :string
add_column :abierta, :p4l_5, :string
add_column :abierta, :p4l_6, :string
add_column :abierta, :p4l_7, :string
add_column :abierta, :p4l_8, :string
add_column :abierta, :p4m_1, :string
add_column :abierta, :p4m_2, :string
add_column :abierta, :p4m_3, :string
add_column :abierta, :p4m_4, :string
add_column :abierta, :p4m_5, :string
add_column :abierta, :p4m_6, :string
add_column :abierta, :p4m_7, :string
add_column :abierta, :p4m_8, :string
add_column :abierta, :p4n_1, :string
add_column :abierta, :p4n_2, :string
add_column :abierta, :p4n_3, :string
add_column :abierta, :p4n_4, :string
add_column :abierta, :p4n_5, :string
add_column :abierta, :p4n_6, :string
add_column :abierta, :p4n_7, :string
add_column :abierta, :p4n_8, :string
add_column :abierta, :p12, :string

  end
end
