class AddEstudiantesP20aP35i < ActiveRecord::Migration[5.2]
  def change
  	add_column :estudiantes, :p20a, :string
  	add_column :estudiantes, :p20b, :string
  	add_column :estudiantes, :p20c, :string
  	add_column :estudiantes, :p21, :string
  	add_column :estudiantes, :p22_1, :string
  	add_column :estudiantes, :p22_2, :string
  	add_column :estudiantes, :p23, :string
  	add_column :estudiantes, :p24a, :string
  	add_column :estudiantes, :p24b, :string
  	add_column :estudiantes, :p24c, :string
  	add_column :estudiantes, :p24d, :string
  	add_column :estudiantes, :p24e, :string
  	add_column :estudiantes, :p24f, :string
  	add_column :estudiantes, :p24g, :string
  	add_column :estudiantes, :p24h, :string
  	add_column :estudiantes, :p24i, :string
  	add_column :estudiantes, :p24j, :string
  	add_column :estudiantes, :p24k, :string
  	add_column :estudiantes, :p24l, :string
  	add_column :estudiantes, :p24m, :string
  	add_column :estudiantes, :p24n, :string
  	add_column :estudiantes, :p24o, :string
  	add_column :estudiantes, :p24p, :string
  	add_column :estudiantes, :p24q, :string
  	add_column :estudiantes, :p24q_1, :string
  	add_column :estudiantes, :p25a, :string
  	add_column :estudiantes, :p25b, :string
  	add_column :estudiantes, :p25c, :string
  	add_column :estudiantes, :p25d, :string
  	add_column :estudiantes, :p25d_1, :string
  	add_column :estudiantes, :p26a, :string
  	add_column :estudiantes, :p26b, :string
  	add_column :estudiantes, :p26c, :string
  	add_column :estudiantes, :p26d, :string
  	add_column :estudiantes, :p26e, :string
  	add_column :estudiantes, :p26f, :string
  	add_column :estudiantes, :p26g, :string
  	add_column :estudiantes, :p26h, :string
  	add_column :estudiantes, :p26i, :string
  	add_column :estudiantes, :p26j, :string
  	add_column :estudiantes, :p26j_1, :string
  	add_column :estudiantes, :p27a, :string
  	add_column :estudiantes, :p27b, :string
  	add_column :estudiantes, :p27c, :string
  	add_column :estudiantes, :p27d, :string
  	add_column :estudiantes, :p27e, :string
  	add_column :estudiantes, :p27f, :string
  	add_column :estudiantes, :p27g, :string
  	add_column :estudiantes, :p27h, :string
  	add_column :estudiantes, :p27h_1, :string
  	add_column :estudiantes, :p28, :string
  	add_column :estudiantes, :p28a, :string
  	add_column :estudiantes, :p29, :string
  	add_column :estudiantes, :p30, :string
  	add_column :estudiantes, :p30a, :string
  	add_column :estudiantes, :p30b, :string
  	add_column :estudiantes, :p30c, :string
  	add_column :estudiantes, :p31a, :string
  	add_column :estudiantes, :p31a_1, :string
  	add_column :estudiantes, :p31b, :string
  	add_column :estudiantes, :p32a, :string
  	add_column :estudiantes, :p32b, :string
  	add_column :estudiantes, :p32c, :string
  	add_column :estudiantes, :p32d, :string
  	add_column :estudiantes, :p32e, :string
  	add_column :estudiantes, :p32f, :string
  	add_column :estudiantes, :p32g, :string
  	add_column :estudiantes, :p32h, :string
  	add_column :estudiantes, :p32i, :string
  	add_column :estudiantes, :p32j, :string
  	add_column :estudiantes, :p32k, :string
  	add_column :estudiantes, :p32k_1, :string
  	add_column :estudiantes, :p33a, :string
  	add_column :estudiantes, :p33b, :string
  	add_column :estudiantes, :p33c, :string
  	add_column :estudiantes, :p33d, :string
  	add_column :estudiantes, :p33e, :string
  	add_column :estudiantes, :p34a, :string
  	add_column :estudiantes, :p34b, :string
  	add_column :estudiantes, :p34c, :string
  	add_column :estudiantes, :p34d, :string
  	add_column :estudiantes, :p34e, :string
  	add_column :estudiantes, :p35a, :string
  	add_column :estudiantes, :p35b, :string
  	add_column :estudiantes, :p35c, :string
  	add_column :estudiantes, :p35d, :string
  	add_column :estudiantes, :p35e, :string
  	add_column :estudiantes, :p35f, :string
  	add_column :estudiantes, :p35g, :string
  	add_column :estudiantes, :p35h, :string
  	add_column :estudiantes, :p35i, :string
  end
end
